### ISSUE TITLE
AgoraRtcKit.framework/AgoraRtcKit' for architecture arm64

### ISSUE THREAD

**Issue by ColtraneNadler** [AgoraIO-Community/react-native-agora#328]
When building on the new macbook with m1 chip, I get this error

```
ld: building for iOS Simulator, but linking in dylib built for iOS, file '/Users/coltrane/Documents/Apps/Storyboard/social/mobile/ios/Pods/AgoraRtcEngine_iOS/AgoraRtcKit.framework/AgoraRtcKit' for architecture arm64
```

any ideas for how to fix?
I tried to excluding arm64 but that breaks other pods. only having this issue with agora pod.

**Comment by LichKing-2234** [comment]
maybe you can try the `3.3.0-rc.1` version.

**Comment by dereknelson** [comment]
@LichKing-2234 i'm working on the `3.3.0-rc.1` version and it gets past the error above, but a new one surfaces: 
```
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "react-native-agora-umbrella.h"
        ^
react_native_agora/react-native-agora-umbrella.h:13:9: note: in file included from ios/Pods/Headers/Public/react_native_agora/react-native-agora-umbrella.h:13:
#import "AgoraRtcEngineKit.h"
        ^
/react-native-agora/ios/RCTAgora/Base/AgoraRtcEngineKit.h:9:9: error: 'AgoraRtcKit/AgoraRtcEngineKit.h' file not found
#import <AgoraRtcKit/AgoraRtcEngineKit.h>
        ^
<unknown>:0: error: could not build Objective-C module 'react_native_agora'
```
i'm using react native 60+ so it's not an autolinking issue, and [i've confirmed that the files exist for arm64](https://prnt.sc/10bml4g). if I [manually drag the agoraRTC framework](https://prnt.sc/10bmmck) I get this error:
```
Showing All Messages
Multiple commands produce 'Xcode/DerivedData/homebody-foicqsbztxgxqidzbrpqullqngmu/Build/Products/Debug-iphonesimulator/app.app/Frameworks/AgoraRtcKit.framework':
1) Target 'homebody' has copy command from ios/Pods/AgoraRtcEngine_iOS/AgoraRtcKit.xcframework/ios-x86_64-simulator/AgoraRtcKit.framework' to '/Users/derek/Library/Developer/Xcode/DerivedData/homebody-foicqsbztxgxqidzbrpqullqngmu/Build/Products/Debug-iphonesimulator/homebody.app/Frameworks/AgoraRtcKit.framework'
2) That command depends on command in Target 'homebody': script phase “[CP] Embed Pods Frameworks”
```
meaning the frameworks are in fact being embedded and signed.

not too sure how to proceed

**Comment by LichKing-2234** [comment]
@dereknelson make sure you are using the latest version of cocoapods and xcode.

**Comment by dereknelson** [comment]
@LichKing-2234 xcode 12.4 pods version 1.10.1

**Comment by LichKing-2234** [comment]
It works for me, could your pls make a demo then I can test it.

**Comment by cdomingopuig** [comment]
I had the same issue. This is what worked for me: https://stackoverflow.com/a/18618187.

**Comment by radko93** [comment]
Are you using ARM Mac? Agora does not support iOS simulators running on ARM right now.

**Comment by maxxfrazer** [comment]
The frameworks are now provided as XCFrameworks with arm64 architecture
